utility: compress_float.cpp prepare_inputfiles.cpp chunk.cpp prepare_denovo.cpp make_haplo_posteriors.cpp split_file.cpp
	g++ -o ../../bin/compress_float compress_float.cpp
#g++ -o ../../bin/prepare_inputfiles prepare_inputfiles.cpp
#g++ -o ../../bin/chunk chunk.cpp
#g++ -o ../../bin/prepare_denovo prepare_denovo.cpp
#g++ -o ../../bin/make_haplo_posteriors make_haplo_posteriors.cpp
#g++ -o ../../bin/split_file split_file.cpp

